---
title: "Project2"
author: 'Lin Li'
output: 
params:
  weekday: 1
---
# Introduction
```{r}
library(dplyr)
library(caret)
library(ggplot2)
library(rmarkdown)
```

```{r,eval=FALSE,echo=FALSE,include=TRUE}
day<-unique(data$weekday)
output_file<-paste0(day,'.md')
params = lapply(day, FUN = function(x){list(weekday = x)})
reports<-tibble(output_file,params)
apply(reports, MARGIN = 1, FUN = function(x){
                render(input = 'Project2.Rmd', output_file = x[[1]], params = x[[2]])
                })

```




# Data
```{r}
# relative path to read data
getwd()
day<-read.csv('day.csv')
day<-day%>%select(-c('casual','registered'))
day
hour<-read.csv('hour.csv')
hour<-hour%>%select(-c('casual','registered'))
# combine two data and get a new one
data<-semi_join(hour,day,by='dteday')
# filter Monday out
date<- filter(data,weekday==params$weekday)
set.seed(100)
# set train/test set
index<-createDataPartition(date$cnt,p=0.7,list=FALSE)
trainday<-date[index,]
testday<-date[-index,]

```


# Summarization
```{r}
# weather
g1<-ggplot(data=trainday,aes(x=factor(weathersit)))+geom_bar()+labs(x='Weather',title='Count for weather')+scale_x_discrete(labels=c('Clear/Cloud','Cloud+Mist','Light rain/snow','Heavy rain..'))
g1
# feeling temp
g2<-ggplot(data=trainday,aes(x=atemp,y=cnt))+geom_point()+labs(x='Normalized feeling temperature',title='Count for atemp')
g2
# humidity
g3<-ggplot(data=trainday,aes(x=hum,y=cnt))+geom_point()+labs(x='Normalized humidity',title='Count for hum')
g3
# windspeed
g4<-ggplot(data=trainday,aes(x=windspeed,y=cnt))+geom_point()+labs(x='Normalized wind speed',title='Count for hum')
g4
# month
g5<-ggplot(data=trainday,aes(x=factor(mnth)))+geom_bar()+labs(x='Month',title='Count for month')+scale_x_discrete(labels=c('Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'))
g5
# season
g6<-ggplot(data=trainday,aes(x=factor(season)))+geom_bar()+labs(x='Season',title='Count for month')+scale_x_discrete(labels=c('winter','spring','summer','fall'))
g6
```


# Modeling

  In this section, I fitted two models. First is classification tree model using leave one out cross validation. Second is boosted tree model using corss-validation.  For both models, I center and scale the quantitative data before modeling.



```{r}
classification.fit<-train(cnt~season+mnth+hr+holiday+workingday+weathersit+temp+atemp+hum+windspeed,trainday,method='rpart',preProcess = c('center','scale'),trControl=trainControl(method='LOOCV'))
classification.fit$bestTune
classification.fit$results
boosted.fit<-train(cnt~season+yr+mnth+hr+holiday+workingday+weathersit+temp+atemp+hum+windspeed,trainday,method='gbm',preProcess = c('center','scale'),trControl=trainControl(method='repeatedcv'), verbose = FALSE)
boosted.fit$bestTune
boosted.fit$results
pred<-round(predict(classification.fit,newdata=testday))
tree.tbl<-table(data.frame(pred=pred,true=testday$cnt))
missclassfication1<-1-sum(diag(tree.tbl))/sum(tree.tbl)
missclassfication1
pred2<-round(predict(boosted.fit,newdata=testday))
boosted.tbl<-table(data.frame(pred=pred2,true=testday$cnt))
missclassfication2<-1-sum(diag(boosted.tbl))/sum(boosted.tbl)
missclassfication2
```

```{r,eval=FALSE,echo=FALSE,include=TRUE}
weekday<-unique(data$weekday)
output_file<-paste0(weekday,'.html')
params<-lapply(weekday, FUN = function(x){list(weekday = x)})
params
reports<-tibble(output_file,params)
reports
apply(reports, MARGIN = 1, FUN = function(x){render(input = 'Project2.Rmd', output_file = x[[1]], params = x[[2]])})
```